package com.zgsu.graduation.model;

import java.util.Date;

public class AppointmentConditions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_conditions.id
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_conditions.conference_initiator
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    private Integer conferenceInitiator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_conditions.numbers
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    private Integer numbers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_conditions.date
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_conditions.start_time
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_conditions.end_time
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_conditions.duration
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    private Integer duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_conditions.is_audio
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    private Boolean isAudio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_conditions.is_mike
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    private Boolean isMike;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_conditions.is_projector
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    private Boolean isProjector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_conditions.state
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_conditions.id
     *
     * @return the value of appointment_conditions.id
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_conditions.id
     *
     * @param id the value for appointment_conditions.id
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_conditions.conference_initiator
     *
     * @return the value of appointment_conditions.conference_initiator
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public Integer getConferenceInitiator() {
        return conferenceInitiator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_conditions.conference_initiator
     *
     * @param conferenceInitiator the value for appointment_conditions.conference_initiator
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public void setConferenceInitiator(Integer conferenceInitiator) {
        this.conferenceInitiator = conferenceInitiator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_conditions.numbers
     *
     * @return the value of appointment_conditions.numbers
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public Integer getNumbers() {
        return numbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_conditions.numbers
     *
     * @param numbers the value for appointment_conditions.numbers
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public void setNumbers(Integer numbers) {
        this.numbers = numbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_conditions.date
     *
     * @return the value of appointment_conditions.date
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_conditions.date
     *
     * @param date the value for appointment_conditions.date
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_conditions.start_time
     *
     * @return the value of appointment_conditions.start_time
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_conditions.start_time
     *
     * @param startTime the value for appointment_conditions.start_time
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_conditions.end_time
     *
     * @return the value of appointment_conditions.end_time
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_conditions.end_time
     *
     * @param endTime the value for appointment_conditions.end_time
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_conditions.duration
     *
     * @return the value of appointment_conditions.duration
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_conditions.duration
     *
     * @param duration the value for appointment_conditions.duration
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_conditions.is_audio
     *
     * @return the value of appointment_conditions.is_audio
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public Boolean getIsAudio() {
        return isAudio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_conditions.is_audio
     *
     * @param isAudio the value for appointment_conditions.is_audio
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public void setIsAudio(Boolean isAudio) {
        this.isAudio = isAudio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_conditions.is_mike
     *
     * @return the value of appointment_conditions.is_mike
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public Boolean getIsMike() {
        return isMike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_conditions.is_mike
     *
     * @param isMike the value for appointment_conditions.is_mike
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public void setIsMike(Boolean isMike) {
        this.isMike = isMike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_conditions.is_projector
     *
     * @return the value of appointment_conditions.is_projector
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public Boolean getIsProjector() {
        return isProjector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_conditions.is_projector
     *
     * @param isProjector the value for appointment_conditions.is_projector
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public void setIsProjector(Boolean isProjector) {
        this.isProjector = isProjector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_conditions.state
     *
     * @return the value of appointment_conditions.state
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_conditions.state
     *
     * @param state the value for appointment_conditions.state
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }
}