package com.zgsu.graduation.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AppointmentConditionsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public AppointmentConditionsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andConferenceInitiatorIsNull() {
            addCriterion("conference_initiator is null");
            return (Criteria) this;
        }

        public Criteria andConferenceInitiatorIsNotNull() {
            addCriterion("conference_initiator is not null");
            return (Criteria) this;
        }

        public Criteria andConferenceInitiatorEqualTo(Integer value) {
            addCriterion("conference_initiator =", value, "conferenceInitiator");
            return (Criteria) this;
        }

        public Criteria andConferenceInitiatorNotEqualTo(Integer value) {
            addCriterion("conference_initiator <>", value, "conferenceInitiator");
            return (Criteria) this;
        }

        public Criteria andConferenceInitiatorGreaterThan(Integer value) {
            addCriterion("conference_initiator >", value, "conferenceInitiator");
            return (Criteria) this;
        }

        public Criteria andConferenceInitiatorGreaterThanOrEqualTo(Integer value) {
            addCriterion("conference_initiator >=", value, "conferenceInitiator");
            return (Criteria) this;
        }

        public Criteria andConferenceInitiatorLessThan(Integer value) {
            addCriterion("conference_initiator <", value, "conferenceInitiator");
            return (Criteria) this;
        }

        public Criteria andConferenceInitiatorLessThanOrEqualTo(Integer value) {
            addCriterion("conference_initiator <=", value, "conferenceInitiator");
            return (Criteria) this;
        }

        public Criteria andConferenceInitiatorIn(List<Integer> values) {
            addCriterion("conference_initiator in", values, "conferenceInitiator");
            return (Criteria) this;
        }

        public Criteria andConferenceInitiatorNotIn(List<Integer> values) {
            addCriterion("conference_initiator not in", values, "conferenceInitiator");
            return (Criteria) this;
        }

        public Criteria andConferenceInitiatorBetween(Integer value1, Integer value2) {
            addCriterion("conference_initiator between", value1, value2, "conferenceInitiator");
            return (Criteria) this;
        }

        public Criteria andConferenceInitiatorNotBetween(Integer value1, Integer value2) {
            addCriterion("conference_initiator not between", value1, value2, "conferenceInitiator");
            return (Criteria) this;
        }

        public Criteria andNumbersIsNull() {
            addCriterion("numbers is null");
            return (Criteria) this;
        }

        public Criteria andNumbersIsNotNull() {
            addCriterion("numbers is not null");
            return (Criteria) this;
        }

        public Criteria andNumbersEqualTo(Integer value) {
            addCriterion("numbers =", value, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersNotEqualTo(Integer value) {
            addCriterion("numbers <>", value, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersGreaterThan(Integer value) {
            addCriterion("numbers >", value, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersGreaterThanOrEqualTo(Integer value) {
            addCriterion("numbers >=", value, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersLessThan(Integer value) {
            addCriterion("numbers <", value, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersLessThanOrEqualTo(Integer value) {
            addCriterion("numbers <=", value, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersIn(List<Integer> values) {
            addCriterion("numbers in", values, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersNotIn(List<Integer> values) {
            addCriterion("numbers not in", values, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersBetween(Integer value1, Integer value2) {
            addCriterion("numbers between", value1, value2, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersNotBetween(Integer value1, Integer value2) {
            addCriterion("numbers not between", value1, value2, "numbers");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(String value) {
            addCriterion("date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(String value) {
            addCriterion("date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(String value) {
            addCriterion("date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(String value) {
            addCriterion("date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(String value) {
            addCriterion("date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(String value) {
            addCriterion("date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLike(String value) {
            addCriterion("date like", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotLike(String value) {
            addCriterion("date not like", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<String> values) {
            addCriterion("date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<String> values) {
            addCriterion("date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(String value1, String value2) {
            addCriterion("date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(String value1, String value2) {
            addCriterion("date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterionForJDBCTime("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterionForJDBCTime("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterionForJDBCTime("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterionForJDBCTime("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterionForJDBCTime("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterionForJDBCTime("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andDurationIsNull() {
            addCriterion("duration is null");
            return (Criteria) this;
        }

        public Criteria andDurationIsNotNull() {
            addCriterion("duration is not null");
            return (Criteria) this;
        }

        public Criteria andDurationEqualTo(Integer value) {
            addCriterion("duration =", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotEqualTo(Integer value) {
            addCriterion("duration <>", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThan(Integer value) {
            addCriterion("duration >", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThanOrEqualTo(Integer value) {
            addCriterion("duration >=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThan(Integer value) {
            addCriterion("duration <", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThanOrEqualTo(Integer value) {
            addCriterion("duration <=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationIn(List<Integer> values) {
            addCriterion("duration in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotIn(List<Integer> values) {
            addCriterion("duration not in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationBetween(Integer value1, Integer value2) {
            addCriterion("duration between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotBetween(Integer value1, Integer value2) {
            addCriterion("duration not between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andIsAudioIsNull() {
            addCriterion("is_audio is null");
            return (Criteria) this;
        }

        public Criteria andIsAudioIsNotNull() {
            addCriterion("is_audio is not null");
            return (Criteria) this;
        }

        public Criteria andIsAudioEqualTo(Boolean value) {
            addCriterion("is_audio =", value, "isAudio");
            return (Criteria) this;
        }

        public Criteria andIsAudioNotEqualTo(Boolean value) {
            addCriterion("is_audio <>", value, "isAudio");
            return (Criteria) this;
        }

        public Criteria andIsAudioGreaterThan(Boolean value) {
            addCriterion("is_audio >", value, "isAudio");
            return (Criteria) this;
        }

        public Criteria andIsAudioGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_audio >=", value, "isAudio");
            return (Criteria) this;
        }

        public Criteria andIsAudioLessThan(Boolean value) {
            addCriterion("is_audio <", value, "isAudio");
            return (Criteria) this;
        }

        public Criteria andIsAudioLessThanOrEqualTo(Boolean value) {
            addCriterion("is_audio <=", value, "isAudio");
            return (Criteria) this;
        }

        public Criteria andIsAudioIn(List<Boolean> values) {
            addCriterion("is_audio in", values, "isAudio");
            return (Criteria) this;
        }

        public Criteria andIsAudioNotIn(List<Boolean> values) {
            addCriterion("is_audio not in", values, "isAudio");
            return (Criteria) this;
        }

        public Criteria andIsAudioBetween(Boolean value1, Boolean value2) {
            addCriterion("is_audio between", value1, value2, "isAudio");
            return (Criteria) this;
        }

        public Criteria andIsAudioNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_audio not between", value1, value2, "isAudio");
            return (Criteria) this;
        }

        public Criteria andIsMikeIsNull() {
            addCriterion("is_mike is null");
            return (Criteria) this;
        }

        public Criteria andIsMikeIsNotNull() {
            addCriterion("is_mike is not null");
            return (Criteria) this;
        }

        public Criteria andIsMikeEqualTo(Boolean value) {
            addCriterion("is_mike =", value, "isMike");
            return (Criteria) this;
        }

        public Criteria andIsMikeNotEqualTo(Boolean value) {
            addCriterion("is_mike <>", value, "isMike");
            return (Criteria) this;
        }

        public Criteria andIsMikeGreaterThan(Boolean value) {
            addCriterion("is_mike >", value, "isMike");
            return (Criteria) this;
        }

        public Criteria andIsMikeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_mike >=", value, "isMike");
            return (Criteria) this;
        }

        public Criteria andIsMikeLessThan(Boolean value) {
            addCriterion("is_mike <", value, "isMike");
            return (Criteria) this;
        }

        public Criteria andIsMikeLessThanOrEqualTo(Boolean value) {
            addCriterion("is_mike <=", value, "isMike");
            return (Criteria) this;
        }

        public Criteria andIsMikeIn(List<Boolean> values) {
            addCriterion("is_mike in", values, "isMike");
            return (Criteria) this;
        }

        public Criteria andIsMikeNotIn(List<Boolean> values) {
            addCriterion("is_mike not in", values, "isMike");
            return (Criteria) this;
        }

        public Criteria andIsMikeBetween(Boolean value1, Boolean value2) {
            addCriterion("is_mike between", value1, value2, "isMike");
            return (Criteria) this;
        }

        public Criteria andIsMikeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_mike not between", value1, value2, "isMike");
            return (Criteria) this;
        }

        public Criteria andIsProjectorIsNull() {
            addCriterion("is_projector is null");
            return (Criteria) this;
        }

        public Criteria andIsProjectorIsNotNull() {
            addCriterion("is_projector is not null");
            return (Criteria) this;
        }

        public Criteria andIsProjectorEqualTo(Boolean value) {
            addCriterion("is_projector =", value, "isProjector");
            return (Criteria) this;
        }

        public Criteria andIsProjectorNotEqualTo(Boolean value) {
            addCriterion("is_projector <>", value, "isProjector");
            return (Criteria) this;
        }

        public Criteria andIsProjectorGreaterThan(Boolean value) {
            addCriterion("is_projector >", value, "isProjector");
            return (Criteria) this;
        }

        public Criteria andIsProjectorGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_projector >=", value, "isProjector");
            return (Criteria) this;
        }

        public Criteria andIsProjectorLessThan(Boolean value) {
            addCriterion("is_projector <", value, "isProjector");
            return (Criteria) this;
        }

        public Criteria andIsProjectorLessThanOrEqualTo(Boolean value) {
            addCriterion("is_projector <=", value, "isProjector");
            return (Criteria) this;
        }

        public Criteria andIsProjectorIn(List<Boolean> values) {
            addCriterion("is_projector in", values, "isProjector");
            return (Criteria) this;
        }

        public Criteria andIsProjectorNotIn(List<Boolean> values) {
            addCriterion("is_projector not in", values, "isProjector");
            return (Criteria) this;
        }

        public Criteria andIsProjectorBetween(Boolean value1, Boolean value2) {
            addCriterion("is_projector between", value1, value2, "isProjector");
            return (Criteria) this;
        }

        public Criteria andIsProjectorNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_projector not between", value1, value2, "isProjector");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table appointment_conditions
     *
     * @mbg.generated do_not_delete_during_merge Sat Feb 15 16:46:02 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}