package com.zgsu.graduation.model;

public class ConferenceParticipant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_participant.id
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_participant.conference_id
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    private Integer conferenceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_participant.participant
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    private Integer participant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_participant.state
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    private Byte state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_participant.id
     *
     * @return the value of conference_participant.id
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_participant.id
     *
     * @param id the value for conference_participant.id
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_participant.conference_id
     *
     * @return the value of conference_participant.conference_id
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    public Integer getConferenceId() {
        return conferenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_participant.conference_id
     *
     * @param conferenceId the value for conference_participant.conference_id
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    public void setConferenceId(Integer conferenceId) {
        this.conferenceId = conferenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_participant.participant
     *
     * @return the value of conference_participant.participant
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    public Integer getParticipant() {
        return participant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_participant.participant
     *
     * @param participant the value for conference_participant.participant
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    public void setParticipant(Integer participant) {
        this.participant = participant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_participant.state
     *
     * @return the value of conference_participant.state
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_participant.state
     *
     * @param state the value for conference_participant.state
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    public void setState(Byte state) {
        this.state = state;
    }
}