package com.zgsu.graduation.model;

import java.util.Date;

public class ConferenceAppointment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_appointment.id
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_appointment.conference_initiator
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    private Integer conferenceInitiator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_appointment.room_id
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_appointment.date
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_appointment.start_time
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_appointment.end_time
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_appointment.theme
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    private String theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_appointment.introduce
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_appointment.state
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_appointment.id
     *
     * @return the value of conference_appointment.id
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_appointment.id
     *
     * @param id the value for conference_appointment.id
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_appointment.conference_initiator
     *
     * @return the value of conference_appointment.conference_initiator
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public Integer getConferenceInitiator() {
        return conferenceInitiator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_appointment.conference_initiator
     *
     * @param conferenceInitiator the value for conference_appointment.conference_initiator
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public void setConferenceInitiator(Integer conferenceInitiator) {
        this.conferenceInitiator = conferenceInitiator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_appointment.room_id
     *
     * @return the value of conference_appointment.room_id
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_appointment.room_id
     *
     * @param roomId the value for conference_appointment.room_id
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_appointment.date
     *
     * @return the value of conference_appointment.date
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_appointment.date
     *
     * @param date the value for conference_appointment.date
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_appointment.start_time
     *
     * @return the value of conference_appointment.start_time
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_appointment.start_time
     *
     * @param startTime the value for conference_appointment.start_time
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_appointment.end_time
     *
     * @return the value of conference_appointment.end_time
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_appointment.end_time
     *
     * @param endTime the value for conference_appointment.end_time
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_appointment.theme
     *
     * @return the value of conference_appointment.theme
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_appointment.theme
     *
     * @param theme the value for conference_appointment.theme
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_appointment.introduce
     *
     * @return the value of conference_appointment.introduce
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_appointment.introduce
     *
     * @param introduce the value for conference_appointment.introduce
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_appointment.state
     *
     * @return the value of conference_appointment.state
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_appointment.state
     *
     * @param state the value for conference_appointment.state
     *
     * @mbg.generated Thu Feb 27 11:15:00 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }
}