package com.zgsu.graduation.model;

public class ConferenceParticipant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_participant.id
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_participant.conference_id
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    private Integer conferenceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_participant.room_id
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_participant.participant
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    private Integer participant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_participant.state
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_participant.mark
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    private Float mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_participant.evaluate
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    private String evaluate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_participant.id
     *
     * @return the value of conference_participant.id
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_participant.id
     *
     * @param id the value for conference_participant.id
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_participant.conference_id
     *
     * @return the value of conference_participant.conference_id
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    public Integer getConferenceId() {
        return conferenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_participant.conference_id
     *
     * @param conferenceId the value for conference_participant.conference_id
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    public void setConferenceId(Integer conferenceId) {
        this.conferenceId = conferenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_participant.room_id
     *
     * @return the value of conference_participant.room_id
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_participant.room_id
     *
     * @param roomId the value for conference_participant.room_id
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_participant.participant
     *
     * @return the value of conference_participant.participant
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    public Integer getParticipant() {
        return participant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_participant.participant
     *
     * @param participant the value for conference_participant.participant
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    public void setParticipant(Integer participant) {
        this.participant = participant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_participant.state
     *
     * @return the value of conference_participant.state
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_participant.state
     *
     * @param state the value for conference_participant.state
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_participant.mark
     *
     * @return the value of conference_participant.mark
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    public Float getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_participant.mark
     *
     * @param mark the value for conference_participant.mark
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    public void setMark(Float mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_participant.evaluate
     *
     * @return the value of conference_participant.evaluate
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    public String getEvaluate() {
        return evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_participant.evaluate
     *
     * @param evaluate the value for conference_participant.evaluate
     *
     * @mbg.generated Fri Mar 27 11:02:48 CST 2020
     */
    public void setEvaluate(String evaluate) {
        this.evaluate = evaluate == null ? null : evaluate.trim();
    }
}