package com.zgsu.graduation.model;

public class Room {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.id
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.name
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.capacity
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    private Integer capacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.audio
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    private Boolean audio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.mike
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    private Boolean mike;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.projector
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    private Boolean projector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.address
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.serial_number
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    private String serialNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.picture
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.state
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    private Boolean state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.remark
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.id
     *
     * @return the value of room.id
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.id
     *
     * @param id the value for room.id
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.name
     *
     * @return the value of room.name
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.name
     *
     * @param name the value for room.name
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.capacity
     *
     * @return the value of room.capacity
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.capacity
     *
     * @param capacity the value for room.capacity
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.audio
     *
     * @return the value of room.audio
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public Boolean getAudio() {
        return audio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.audio
     *
     * @param audio the value for room.audio
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public void setAudio(Boolean audio) {
        this.audio = audio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.mike
     *
     * @return the value of room.mike
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public Boolean getMike() {
        return mike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.mike
     *
     * @param mike the value for room.mike
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public void setMike(Boolean mike) {
        this.mike = mike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.projector
     *
     * @return the value of room.projector
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public Boolean getProjector() {
        return projector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.projector
     *
     * @param projector the value for room.projector
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public void setProjector(Boolean projector) {
        this.projector = projector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.address
     *
     * @return the value of room.address
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.address
     *
     * @param address the value for room.address
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.serial_number
     *
     * @return the value of room.serial_number
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.serial_number
     *
     * @param serialNumber the value for room.serial_number
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.picture
     *
     * @return the value of room.picture
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.picture
     *
     * @param picture the value for room.picture
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.state
     *
     * @return the value of room.state
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.state
     *
     * @param state the value for room.state
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.remark
     *
     * @return the value of room.remark
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.remark
     *
     * @param remark the value for room.remark
     *
     * @mbg.generated Wed Feb 12 16:20:38 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}