package com.zgsu.graduation.mapper;

import com.zgsu.graduation.model.AppointmentConditions;
import com.zgsu.graduation.model.AppointmentConditionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;

@Component
public interface AppointmentConditionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    long countByExample(AppointmentConditionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    int deleteByExample(AppointmentConditionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    int insert(AppointmentConditions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    int insertSelective(AppointmentConditions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    List<AppointmentConditions> selectByExampleWithRowbounds(AppointmentConditionsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    List<AppointmentConditions> selectByExample(AppointmentConditionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    AppointmentConditions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    int updateByExampleSelective(@Param("record") AppointmentConditions record, @Param("example") AppointmentConditionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    int updateByExample(@Param("record") AppointmentConditions record, @Param("example") AppointmentConditionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    int updateByPrimaryKeySelective(AppointmentConditions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_conditions
     *
     * @mbg.generated Sat Feb 15 16:46:02 CST 2020
     */
    int updateByPrimaryKey(AppointmentConditions record);
}