package com.zgsu.graduation.mapper;

import com.zgsu.graduation.model.ConferenceParticipant;
import com.zgsu.graduation.model.ConferenceParticipantExample;

import java.util.List;

import io.swagger.models.auth.In;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;

@Component
public interface ConferenceParticipantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conference_participant
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    long countByExample(ConferenceParticipantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conference_participant
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    int deleteByExample(ConferenceParticipantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conference_participant
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conference_participant
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    int insert(ConferenceParticipant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conference_participant
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    int insertSelective(ConferenceParticipant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conference_participant
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    List<ConferenceParticipant> selectByExampleWithRowbounds(ConferenceParticipantExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conference_participant
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    List<ConferenceParticipant> selectByExample(ConferenceParticipantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conference_participant
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    ConferenceParticipant selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conference_participant
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    int updateByExampleSelective(@Param("record") ConferenceParticipant record, @Param("example") ConferenceParticipantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conference_participant
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    int updateByExample(@Param("record") ConferenceParticipant record, @Param("example") ConferenceParticipantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conference_participant
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    int updateByPrimaryKeySelective(ConferenceParticipant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conference_participant
     *
     * @mbg.generated Wed Feb 12 14:33:43 CST 2020
     */
    int updateByPrimaryKey(ConferenceParticipant record);

    @Select("select last_insert_id()")
    int selectLastId();

    //根据会议id查找参会者的idlist
    @Select("select participant from conference+participant where conference_id=#{conferenceId}")
    List<Integer> selectByConferenceId(@Param("conferenceId")Integer conferenceId);

    @Select("select state from conference_participant where conference_id=#{conferenceId} and participant=#{participantId}")
    Integer selectState(@Param("conferenceId")Integer conferenceId,@Param("participantId") Integer participantId);
    @Update("update conference_participant set state=#{state} where conference_id=#{conferenceId} and participant=#{participantId}")
    Integer updateState(@Param("conferenceId")Integer conferenceId,@Param("participantId") Integer participantId,@Param("state")Integer state);
}